# Generated by Django 6.0.2 on 2026-02-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='days_to_service',
            new_name='days_till_service',
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_service',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
