# Generated by Django 6.0.2 on 2026-05-28 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_equipment_days_till_service_equipmentrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentrequest',
            options={'ordering': ['-date_requested']},
        ),
        migrations.RenameField(
            model_name='equipmentrequest',
            old_name='created_at',
            new_name='date_requested',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='days_till_service',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='next_service',
        ),
        migrations.RemoveField(
            model_name='equipmentrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='requester_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='requester_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='inventory.equipment'),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
