# Generated by Django 6.0.2 on 2026-06-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_equipmentrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequest',
            name='request_type',
            field=models.CharField(choices=[('service  ', 'Service'), ('repair', 'Repair'), ('other', 'Other')], default='', max_length=50),
        ),
    ]
