# Generated by Django 6.0.2 on 2026-06-17 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_equipmentrequest_request_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('serviced', 'Serviced'), ('request', 'Request')], max_length=20)),
                ('description', models.TextField()),
                ('performed_by', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.equipment')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
