# Generated by Django 6.0.2 on 2026-06-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_equipmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenthistory',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='status',
            field=models.CharField(default='completed', max_length=20),
        ),
    ]
